import { colors } from '../../../helpers/styles';
import {
  CircleMember,
  CircleNotification,
  SharedOffer,
} from './types';

export const ALL_CONTACTS: CircleMember[] = [
  {
    id: 'you',
    name: 'Azmir',
    phone: '+91 77777 88888',
    role: 'Admin',
    isYou: true,
    online: true,
    avatarColor: colors.primarySoft,
    initial: 'A',
    registered: true,
  },
  {
    id: 'papa',
    name: 'Papa',
    phone: '+91 98765 43210',
    role: 'Co-Admin',
    online: true,
    avatarColor: colors.pastelBlue,
    initial: 'P',
    registered: true,
  },
  {
    id: 'mama',
    name: 'Mama',
    phone: '+91 98765 43211',
    role: 'Member',
    online: true,
    avatarColor: colors.pastelPurple,
    initial: 'M',
    registered: true,
  },
  {
    id: 'imran',
    name: 'Imran Khan',
    phone: '+91 91234 56780',
    role: 'Member',
    online: true,
    avatarColor: colors.pastelOrange,
    initial: 'I',
    registered: true,
  },
  {
    id: 'sister',
    name: 'Sister',
    phone: '+91 99887 66554',
    role: 'Member',
    online: false,
    avatarColor: colors.pastelPurple,
    initial: 'S',
    registered: true,
  },
  {
    id: 'aman',
    name: 'Aman Sharma',
    phone: '+91 90123 45678',
    role: 'Member',
    online: true,
    avatarColor: colors.combinedColor,
    initial: 'A',
    registered: true,
  },
  {
    id: 'sana',
    name: 'Sana Parveen',
    phone: '+91 90909 10101',
    role: 'Member',
    online: false,
    avatarColor: colors.pastelGreen,
    initial: 'S',
    registered: true,
  },
  {
    id: 'rohit',
    name: 'Rohit Verma',
    phone: '+91 93456 78123',
    role: 'Member',
    online: false,
    avatarColor: colors.pastelYellow,
    initial: 'R',
    registered: true,
  },
  {
    id: 'vivek',
    name: 'Vivek Singh',
    phone: '+91 97654 32109',
    role: 'Member',
    avatarColor: colors.pastelOrange,
    initial: 'V',
    registered: false,
    invitePending: true,
  },
  {
    id: 'neha',
    name: 'Neha Gupta',
    phone: '+91 96543 21098',
    role: 'Member',
    avatarColor: colors.pastelYellow,
    initial: 'N',
    registered: false,
    invitePending: true,
  },
];

export const MOCK_SHARED_OFFERS: SharedOffer[] = [
  {
    id: 'offer-1',
    sharedById: 'you',
    sharedByName: 'You',
    timeAgo: '2h ago',
    brand: "Domino's Pizza",
    title: 'Flat 50% OFF on All Medium Pizzas',
    badge: '50% OFF',
    distance: '1.2 km',
    validTill: '15 May',
    rating: '4.3',
    ratingCount: '256',
    imageColor: colors.pastelYellow,
    about:
      'Enjoy flat 50% off on all medium pizzas. Valid for dine-in, takeaway & delivery. Cannot be clubbed with other offers.',
    address: 'Gorakhpur Bypass Road, Ramgarh Tal, Gorakhpur, UP 273014',
    hours: '10:00 AM – 11:00 PM',
    open: true,
  },
  {
    id: 'offer-2',
    sharedById: 'papa',
    sharedByName: 'Papa',
    timeAgo: '5h ago',
    brand: 'Burger King',
    title: 'Buy 1 Get 1 on Whoppers',
    badge: 'BUY 1 GET 1',
    distance: '2.4 km',
    validTill: '20 May',
    rating: '4.1',
    imageColor: colors.pastelOrange,
    about: 'Buy one Whopper and get another free. Participating outlets only.',
    address: 'Civil Lines, Gorakhpur, UP',
    hours: '11:00 AM – 10:30 PM',
    open: true,
  },
  {
    id: 'offer-3',
    sharedById: 'sister',
    sharedByName: 'Sister',
    timeAgo: '1d ago',
    brand: 'Trends',
    title: 'Flat 70% OFF on Summer Collection',
    badge: '70% OFF',
    distance: '3.1 km',
    validTill: '30 May',
    rating: '4.5',
    imageColor: colors.pastelPurple,
    about: 'Season end sale on summer wear. In-store only.',
    address: 'Golghar Market, Gorakhpur, UP',
    hours: '10:30 AM – 9:00 PM',
    open: true,
  },
];

export const MOCK_NOTIFICATIONS: CircleNotification[] = [
  {
    id: 'n1',
    type: 'shared',
    title: 'Azmir shared an offer with you!',
    subtitle: "Domino's Pizza – Flat 50% OFF on All Medium Pizzas.",
    timeAgo: '2m ago',
    unread: true,
    circleName: "Azmir's Family Circle",
    badge: '50% OFF',
  },
  {
    id: 'n2',
    type: 'shared',
    title: 'Sister shared an offer with you!',
    subtitle: 'Trends – Flat 70% OFF on Summer Collection.',
    timeAgo: '1h ago',
    circleName: "Azmir's Family Circle",
    badge: '70% OFF',
  },
  {
    id: 'n3',
    type: 'joined',
    title: 'Imran Khan joined the circle.',
    subtitle: "Imran Khan is now a member of Azmir's Family Circle.",
    timeAgo: '3h ago',
  },
  {
    id: 'n4',
    type: 'welcome',
    title: 'Welcome to Bachat Circle!',
    subtitle: 'Start sharing the best offers and save more together.',
    timeAgo: '1d ago',
  },
  {
    id: 'n5',
    type: 'new-offer',
    title: 'New offer in your circle!',
    subtitle: 'Pizza Hut – Buy 1 Get 1 Free on All Pizzas.',
    timeAgo: '1d ago',
    badge: 'BUY 1 GET 1',
  },
  {
    id: 'n6',
    type: 'reward',
    title: 'You earned a reward!',
    subtitle: 'Congrats! You earned 50 points for sharing an offer.',
    timeAgo: '2d ago',
    points: '+50 Points',
  },
];

export const DEFAULT_SELECTED_MEMBER_IDS = [
  'aman',
  'imran',
  'sana',
  'papa',
];
